openapi: 3.0.0
info:
  title: Conectando Huellas API
  description: 'API construida con Express y documentada con Swagger.'
  version: 1.0.0

servers:
  - url: http://localhost:9090/api
    description: Servidor de desarrollo
  - url: https://mir-conectando-huellas-backend.onrender.com/
    description: Servidor de producción

tags:
  - name: Auth
    description: Operaciones relacionadas con la autenticación de usuarios
  - name: Users
    description: Operaciones relacionadas con los usuarios
  - name: Species
    description: Operaciones relacionadas con las especies
  - name: Images
    description: Operaciones relacionadas con las imágenes de las mascotas
  - name: LostPets
    description: Operaciones relacionadas con las mascotas perdidas
  - name: AdoptionPets
    description: Operaciones relacionadas con las mascotas en adopción

paths:
  # AUTH
  /users/login:
    post:
      tags:
        - Auth
      summary: Iniciar sesión

  /users/verify/{token}:
    get:
      tags:
        - Auth
      summary: Verificar cuenta

  # USERS
  /users:
    post:
      tags:
        - Users
      summary: Crear un usuario

  /users/{id}:
    get:
      tags:
        - Users
      summary: Obtener un usuario por ID

    put:
      tags:
        - Users
      summary: Actualizar un usuario

  /users/email/{email}:
    get:
      tags:
        - Users
      summary: Obtener un usuario por correo electrónico

  # SPECIES
  /species:
    get:
      tags:
        - Species
      summary: Obtener especies

    post:
      tags:
        - Species
      summary: Crear especie

  /species/{id}:
    get:
      tags:
        - Species
      summary: Obtener especie por ID

    put:
      tags:
        - Species
      summary: Actualizar especie

  # IMAGES
  /images/upload:
    post:
      tags:
        - Images
      summary: Carga una imagen

  /images/delete/{petId}:
    delete:
      tags:
        - Images
      summary: Borrar imagen

  # LOSTPETS
  /lostpets:
    get:
      tags:
        - LostPets
      summary: Obtener mascotas perdidas

    post:
      tags:
        - LostPets
      summary: Crear mascota perdida

    put:
      tags:
        - LostPets
      summary: Actualizar mascota perdida


  /lostpets/{id}:
    get:
      tags:
        - LostPets
      summary: Obtener mascota perdida por ID

  /lostpets/filters/{filter}:
    get:
      tags:
        - LostPets
      summary: Obtener mascotas perdidas filtradas

  /lostpets/user/{userId}:
    get:
      tags:
        - LostPets
      summary: Obtener mascotas perdidas por usuario

# ADOPTIONPETS
  /adoptionpets:
    get:
      tags:
        - AdoptionPets
      summary: Obtener mascotas en adopción

    post:
      tags:
        - AdoptionPets
      summary: Crear mascota en adopción

    put:
      tags:
        - AdoptionPets
      summary: Actualizar mascota en adopción


  /adoptionpets/{id}:
    get:
      tags:
        - AdoptionPets
      summary: Obtener mascota en adopción por ID

  /adoptionpets/filters/{filter}:
    get:
      tags:
        - AdoptionPets
      summary: Obtener mascotas en adopción filtradas

  /adoptionpets/user/{userId}:
    get:
      tags:
        - AdoptionPets
      summary: Obtener mascotas en adopción por usuario

